version: "3.3"

services:
  dsam-notification-bot:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./db/:/app/db/
    restart: unless-stopped
